# This rule is not used by the project courier itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over courier.sororlab.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: courier
    app.kubernetes.io/managed-by: kustomize
  name: oauthclient-admin-role
rules:
- apiGroups:
  - courier.sororlab.dev
  resources:
  - oauthclients
  verbs:
  - '*'
- apiGroups:
  - courier.sororlab.dev
  resources:
  - oauthclients/status
  verbs:
  - get
