# This rule is not used by the project courier itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to courier.sororlab.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: courier
    app.kubernetes.io/managed-by: kustomize
  name: oauthclient-viewer-role
rules:
- apiGroups:
  - courier.sororlab.dev
  resources:
  - oauthclients
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - courier.sororlab.dev
  resources:
  - oauthclients/status
  verbs:
  - get
